package com.Gestion.MiBalnearioGestion.Auth.Permisos;

public enum Permisos {
    RECURSOS_VER, RECURSOS_CREAR, RECURSOS_MODIFICAR, RECURSOS_ELIMINAR,

    PAGOS_VER, PAGOS_CREAR, PAGOS_MODIFICAR, PAGOS_ELIMINAR,

    RESERVAS_VER, RESERVAS_CREAR, RESERVAS_MODIFICAR, RESERVAS_ELIMINAR,

    MENU_VER, MENU_CREAR, MENU_MODIFICAR, MENU_ELIMINAR,

    PEDIDOS_VER, PEDIDOS_CREAR, PEDIDOS_MODIFICAR, PEDIDOS_ELIMINAR,

    EMPLEADOS_VER, EMPLEADOS_CREAR, EMPLEADOS_MODIFICAR, EMPLEADOS_ELIMINAR,

    CLIENTES_VER, CLIENTES_CREAR, CLIENTES_MODIFICAR, CLIENTES_ELIMINAR,

    USUARIOS_VER, USUARIOS_CREAR, USUARIOS_MODIFICAR, USUARIOS_ELIMINAR
}