spring:
  application:
    name: MiBalnearioGestion

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

mp:
  accesstoken: ${MP_ACCESS_TOKEN}
  webhook: "https://culinary-bleep-woof.ngrok-free.dev/api/v1/public/webhooks/mercadopago"
  backurl:
    success: "https://culinary-bleep-woof.ngrok-free.dev/pago-exitoso"
    failure: "https://culinary-bleep-woof.ngrok-free.dev/pago-fallido"
  backurls:
    success: "https://culinary-bleep-woof.ngrok-free.dev/pago-exitoso"
    failure: "https://culinary-bleep-woof.ngrok-free.dev/pago-fallido"

mail:
    host: smtp.gmail.com
    port: 587
    username: balnearioapiutn@gmail.com
    password: ${GMAIL_APP}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
